#!/usr/bin/env node
/* build-wizard.js — bundle tools/dashboard/* into the single-file tools/ds-setup.cjs
 *
 * The DELIVERED product stays exactly one zero-dependency file (non-negotiable #2).
 * Only authoring changes: the UI is written as real HTML/CSS/JS with editor support,
 * and this script inlines everything — including the fonts as base64, so the panel
 * never touches the network.
 *
 *   node tools/build-wizard.js            build
 *   node tools/build-wizard.js --check    fail if the committed output is stale (CI)
 */
const fs = require("fs");
const path = require("path");

const DS = path.resolve(__dirname, "..");
const D = path.join(DS, "tools", "dashboard");
const SERVER = path.join(DS, "tools", "wizard-server.js");
const OUT = path.join(DS, "tools", "ds-setup.cjs");
const CHECK = process.argv.includes("--check");

const meta = JSON.parse(fs.readFileSync(path.join(DS, "version.json"), "utf8"));
const read = (f) => fs.readFileSync(path.join(D, f), "utf8");

/* ---- fonts -> base64 @font-face ---- */
function fontFace(family, file, extra) {
  const b64 = fs.readFileSync(path.join(D, "fonts", file)).toString("base64");
  return `@font-face{font-family:"${family}";font-style:normal;font-display:swap;${extra}` +
         `src:url(data:font/woff2;base64,${b64}) format("woff2");}`;
}
const fonts = [
  "/* Fustat — SIL Open Font License 1.1 — the design system's own primary typeface */",
  fontFace("Fustat", "fustat-latin-wght-normal.woff2", "font-weight:200 800;"),
  "/* DM Mono — SIL Open Font License 1.1 */",
  fontFace("DM Mono", "dm-mono-latin-400-normal.woff2", "font-weight:400;"),
].join("\n");

/* ---- assemble the UI document ---- */
let css = read("app.css").replace("/* @FONTS@ */", fonts);
let js = read("app.js").replace("/* @I18N@ */ {}", read("i18n.json").trim());
const icons = read("icons.svg").trim();

let html = read("index.html")
  .replace("/* @CSS@ */", () => css)
  .replace("<!-- @ICONS@ -->", () => icons)
  .replace("/* @JS@ */", () => js);

/* sanity: no placeholder survived, no network reference sneaked in */
for (const bad of ["@CSS@", "@JS@", "@ICONS@", "@FONTS@", "@I18N@"]) {
  if (html.includes(bad)) { console.error(`build-wizard: placeholder ${bad} was not replaced`); process.exit(1); }
}
for (const net of ["fonts.googleapis.com", "fonts.gstatic.com", "cdn.jsdelivr", "unpkg.com", "cdnjs."]) {
  if (html.includes(net)) { console.error(`build-wizard: external reference "${net}" is not allowed — the panel must work offline`); process.exit(1); }
}

/* ---- bundle ---- */
const server = fs.readFileSync(SERVER, "utf8");
const banner =
`#!/usr/bin/env node
/* =====================================================================
   E-Systems Design System — Panel  (single file, zero dependencies)
   =====================================================================
   GENERATED by tools/build-wizard.js from tools/dashboard/ + tools/wizard-server.js.
   Do not edit this file by hand — edit the sources and re-run the build.

   USE
     1. Copy this file into the ROOT of your frontend repo.
     2. node ds-setup.cjs
     3. Your browser opens the panel. Review the plan, then Process.

   PROMISES
     - Plan-first: every command and file change is shown BEFORE it runs.
     - Marked: everything written is wrapped in design-system markers.
     - Reversible: an install receipt (.ds/manifest.json) drives an exact revert.
     - Recoverable: nothing is deleted, only moved to .ds/.trash/.
     - Offline: fonts and icons are embedded. It never phones home.
     - Local: binds to 127.0.0.1 only.

   Embedded fonts: Fustat & DM Mono, SIL Open Font License 1.1.
   Embedded icons: Lucide, ISC License.

   Panel v${meta.wizardVersion}  \u00b7  built for design system v${meta.version}
   ===================================================================== */
`;

const body = server
  .replace("/* @WIZARD_VERSION@ */", JSON.stringify(meta.wizardVersion))
  .replace("/* @DS_VERSION@ */", JSON.stringify(meta.version))
  .replace('"@@PAYLOAD_CLAUDE@@"', JSON.stringify(fs.readFileSync(path.join(DS, "tools", "payloads", "CLAUDE.md"), "utf8")))
  .replace('"@@PAYLOAD_BINDINGS@@"', JSON.stringify(fs.readFileSync(path.join(DS, "tools", "payloads", "bindings.md"), "utf8")))
  .replace('"/* @UI_HTML@ */"', JSON.stringify(html));

for (const bad of ["@@PAYLOAD_CLAUDE@@", "@@PAYLOAD_BINDINGS@@", "@WIZARD_VERSION@", "@UI_HTML@"]) {
  if (body.includes(bad)) { console.error(`build-wizard: placeholder ${bad} was not replaced`); process.exit(1); }
}

const outText = banner + body;

if (CHECK) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (cur !== outText) {
    console.error("\u274c tools/ds-setup.cjs is stale. Run: node tools/build-wizard.js");
    process.exit(1);
  }
  console.log("\u2705 tools/ds-setup.cjs is up to date");
  process.exit(0);
}

fs.writeFileSync(OUT, outText, "utf8");
fs.chmodSync(OUT, 0o755);

const kb = (n) => (n / 1024).toFixed(1) + " KB";
console.log(`build-wizard: tools/ds-setup.cjs \u2192 ${kb(outText.length)}`);
console.log(`  ui ${kb(html.length)} \u00b7 css ${kb(css.length)} \u00b7 js ${kb(js.length)} \u00b7 icons ${kb(icons.length)} \u00b7 fonts ${kb(fonts.length)}`);
